### ISSUE TITLE
AttributeError: 'IMMUcanROIWidget' object has no attribute 'immucan_roi_layer'

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/immucan-roi#10]
Hi @jwindhager 

when trying to draw a roi, `napari-roi` crashed. When trying to open it again, the following error appears:

```
Traceback (most recent call last):
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi-2/bin/immucan-roi", line 8, in <module>
    sys.exit(main())
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi-2/lib/python3.9/site-packages/immucan_roi/__main__.py", line 21, in main
    app.exec_dialog()
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi-2/lib/python3.9/site-packages/napping/_napping_application.py", line 133, in exec_dialog
    self.exec(app=app)
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi-2/lib/python3.9/site-packages/napping/_napping_application.py", line 40, in exec
    self._current_source_viewer = self._create_source_viewer(
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi-2/lib/python3.9/site-packages/immucan_roi/_immucan_roi.py", line 106, in _create_source_viewer
    immucan_roi_widget.load_roi_file()
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi-2/lib/python3.9/site-packages/napari_roi/_roi_widget.py", line 171, in load_roi_file
    self._roi_layer_accessor.append(roi)
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi-2/lib/python3.9/_collections_abc.py", line 1073, in append
    self.insert(len(self), value)
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi-2/lib/python3.9/site-packages/napari_roi/qt/_roi_layer_accessor.py", line 251, in insert
    ROILayerAccessor.ItemAccessor(self, index).insert(roi)
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi-2/lib/python3.9/site-packages/napari_roi/qt/_roi_layer_accessor.py", line 38, in insert
    self._parent._layer.data = layer_data  # appends a row to features
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi-2/lib/python3.9/site-packages/napari/layers/shapes/shapes.py", line 687, in data
    self.add(
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi-2/lib/python3.9/site-packages/napari/layers/shapes/shapes.py", line 2032, in add
    self.events.data(value=self.data)
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi-2/lib/python3.9/site-packages/napari/utils/events/event.py", line 715, in __call__
    self._invoke_callback(cb, event if pass_event else None)
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi-2/lib/python3.9/site-packages/napari/utils/events/event.py", line 752, in _invoke_callback
    _handle_exception(
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi-2/lib/python3.9/site-packages/napari/utils/events/event.py", line 739, in _invoke_callback
    cb(event)
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi-2/lib/python3.9/site-packages/napari_roi/_roi_widget.py", line 347, in _on_roi_layer_data_changed
    self.save_roi_file()
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi-2/lib/python3.9/site-packages/immucan_roi/_immucan_roi_widget.py", line 37, in save_roi_file
    if self._roi_layer == self.immucan_roi_layer:
AttributeError: 'IMMUcanROIWidget' object has no attribute 'immucan_roi_layer'
```

This is the environment:

```
# packages in environment at /Users/immucan/opt/anaconda3/envs/immucan-roi-2:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
appnope                   0.1.2                    pypi_0    pypi
asttokens                 2.0.5                    pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
babel                     2.9.1                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
black                     22.1.0                   pypi_0    pypi
ca-certificates           2021.10.26           hecd8cb5_2  
cachey                    0.2.1                    pypi_0    pypi
certifi                   2021.10.8        py39hecd8cb5_2  
charset-normalizer        2.0.11                   pypi_0    pypi
click                     8.0.3                    pypi_0    pypi
cloudpickle               2.0.0                    pypi_0    pypi
czifile                   2019.7.2                 pypi_0    pypi
dask                      2022.1.1                 pypi_0    pypi
debugpy                   1.5.1                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
docstring-parser          0.13                     pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
executing                 0.8.2                    pypi_0    pypi
freetype-py               2.2.0                    pypi_0    pypi
fsspec                    2022.1.0                 pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
hsluv                     5.0.2                    pypi_0    pypi
idna                      3.3                      pypi_0    pypi
imagecodecs               2021.11.20               pypi_0    pypi
imageio                   2.15.0                   pypi_0    pypi
imagesize                 1.3.0                    pypi_0    pypi
immucan-roi               0.2.1                    pypi_0    pypi
importlib-metadata        4.10.1                   pypi_0    pypi
intervaltree              3.1.0                    pypi_0    pypi
ipykernel                 6.9.0                    pypi_0    pypi
ipython                   8.0.1                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.0.3                    pypi_0    pypi
jsonschema                4.4.0                    pypi_0    pypi
jupyter-client            7.1.2                    pypi_0    pypi
jupyter-core              4.9.1                    pypi_0    pypi
kiwisolver                1.3.2                    pypi_0    pypi
libcxx                    12.0.0               h2f01273_0  
libffi                    3.3                  hb1e8313_2  
locket                    0.2.1                    pypi_0    pypi
magicgui                  0.3.4                    pypi_0    pypi
markupsafe                2.0.1                    pypi_0    pypi
matplotlib-inline         0.1.3                    pypi_0    pypi
mypy-extensions           0.4.3                    pypi_0    pypi
napari                    0.4.14                   pypi_0    pypi
napari-console            0.0.4                    pypi_0    pypi
napari-czifile2           0.2.6                    pypi_0    pypi
napari-imc                0.6.4                    pypi_0    pypi
napari-plugin-engine      0.2.0                    pypi_0    pypi
napari-roi                0.1.3                    pypi_0    pypi
napari-svg                0.1.6                    pypi_0    pypi
napping                   0.2.2                    pypi_0    pypi
ncurses                   6.3                  hca72f7f_2  
nest-asyncio              1.5.4                    pypi_0    pypi
networkx                  2.6.3                    pypi_0    pypi
npe2                      0.1.2                    pypi_0    pypi
numpy                     1.22.2                   pypi_0    pypi
numpydoc                  1.2                      pypi_0    pypi
openssl                   1.1.1m               hca72f7f_0  
packaging                 21.3                     pypi_0    pypi
pandas                    1.4.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
partd                     1.2.0                    pypi_0    pypi
pathspec                  0.9.0                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.0.1                    pypi_0    pypi
pint                      0.18                     pypi_0    pypi
pip                       21.2.4           py39hecd8cb5_0  
platformdirs              2.5.0                    pypi_0    pypi
pooch                     1.6.0                    pypi_0    pypi
prompt-toolkit            3.0.27                   pypi_0    pypi
psutil                    5.9.0                    pypi_0    pypi
psygnal                   0.2.0                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pydantic                  1.9.0                    pypi_0    pypi
pygments                  2.11.2                   pypi_0    pypi
pyopengl                  3.1.5                    pypi_0    pypi
pyparsing                 3.0.7                    pypi_0    pypi
pyqt5                     5.15.6                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.9.1                   pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
python                    3.9.7                h88f2d9e_1  
python-dateutil           2.8.2                    pypi_0    pypi
pytomlpp                  1.0.10                   pypi_0    pypi
pytz                      2021.3                   pypi_0    pypi
pywavelets                1.2.0                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     22.3.0                   pypi_0    pypi
qtconsole                 5.2.2                    pypi_0    pypi
qtpy                      2.0.1                    pypi_0    pypi
readimc                   0.6.1                    pypi_0    pypi
readline                  8.1.2                hca72f7f_1  
requests                  2.27.1                   pypi_0    pypi
scikit-image              0.19.1                   pypi_0    pypi
scipy                     1.8.0                    pypi_0    pypi
setuptools                58.0.4           py39hecd8cb5_0  
six                       1.16.0                   pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
sphinx                    4.4.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.37.2               h707629a_0  
stack-data                0.1.4                    pypi_0    pypi
superqt                   0.2.5.post1              pypi_0    pypi
tifffile                  2022.2.9                 pypi_0    pypi
tk                        8.6.11               h7bc2e8c_0  
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.11.2                   pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
tqdm                      4.62.3                   pypi_0    pypi
traitlets                 5.1.1                    pypi_0    pypi
typer                     0.4.0                    pypi_0    pypi
typing-extensions         4.0.1                    pypi_0    pypi
tzdata                    2021e                hda174b7_0  
urllib3                   1.26.8                   pypi_0    pypi
vispy                     0.9.6                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
wrapt                     1.13.3                   pypi_0    pypi
xz                        5.2.5                h1de35cc_0  
zipp                      3.7.0                    pypi_0    pypi
zlib                      1.2.11               h4dc903c_4  
```

**Comment by jwindhager** [comment]
Apologies - fixed with v0.2.2
