### ISSUE TITLE
when shape feature activated and autosave checked addition of ROI still crashes

### ISSUE THREAD

**Issue by SchulzDan** [BodenmillerGroup/immucan-roi#4]
11:19 AM

/home/dan/miniconda3/envs/napari_roi/lib/python3.9/site-packages/napari/vispy/layers/image.py:224: UserWarning: data shape (34896, 31293) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
/home/dan/miniconda3/envs/napari_roi/lib/python3.9/site-packages/napari/vispy/layers/image.py:224: UserWarning: data shape (34896, 31293) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
/home/dan/miniconda3/envs/napari_roi/lib/python3.9/site-packages/napari/_vispy/layers/image.py:224: UserWarning: data shape (34896, 31293) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
/home/dan/miniconda3/envs/napari_roi/lib/python3.9/site-packages/napari/_vispy/layers/image.py:224: UserWarning: data shape (34896, 31293) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
/home/dan/miniconda3/envs/napari_roi/lib/python3.9/site-packages/napari/_vispy/layers/image.py:224: UserWarning: data shape (34896, 31293) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
/home/dan/miniconda3/envs/napari_roi/lib/python3.9/site-packages/napari/_vispy/layers/image.py:224: UserWarning: data shape (34896, 31293) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
/home/dan/miniconda3/envs/napari_roi/lib/python3.9/site-packages/napari/_vispy/layers/image.py:224: UserWarning: data shape (34896, 31293) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
/home/dan/miniconda3/envs/napari_roi/lib/python3.9/site-packages/napari/_vispy/layers/image.py:224: UserWarning: data shape (34896, 31293) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
WARNING: Traceback (most recent call last):
  File "/home/dan/miniconda3/envs/napari_roi/lib/python3.9/site-packages/napari_roi/_roi_widget.py", line 249, in _on_add_roi_button_clicked
    self._roi_layer_accessor.append(roi)
  File "/home/dan/miniconda3/envs/napari_roi/lib/python3.9/_collections_abc.py", line 1073, in append
    self.insert(len(self), value)
  File "/home/dan/miniconda3/envs/napari_roi/lib/python3.9/site-packages/napari_roi/_qt/roi_layer_accessor.py", line 229, in insert
    ROILayerAccessor.Item(self, index).insert(roi)
  File "/home/dan/miniconda3/envs/napari_roi/lib/python3.9/site-packages/napari_roi/_qt/roi_layer_accessor.py", line 46, in insert
    self._parent._layer.data = layer_data
  File "/home/dan/miniconda3/envs/napari_roi/lib/python3.9/site-packages/napari/layers/shapes/shapes.py", line 688, in data
    self.add(
  File "/home/dan/miniconda3/envs/napari_roi/lib/python3.9/site-packages/napari/layers/shapes/shapes.py", line 2008, in add
    self.events.data(value=self.data)
  File "/home/dan/miniconda3/envs/napari_roi/lib/python3.9/site-packages/napari/utils/events/event.py", line 599, in __call
    self._invoke_callback(cb, event)
  File "/home/dan/miniconda3/envs/napari_roi/lib/python3.9/site-packages/napari/utils/events/event.py", line 631, in _invoke_callback
    _handle_exception(
  File "/home/dan/miniconda3/envs/napari_roi/lib/python3.9/site-packages/napari/utils/events/event.py", line 620, in _invoke_callback
    cb(event)
  File "/home/dan/miniconda3/envs/napari_roi/lib/python3.9/site-packages/napari_roi/_roi_widget.py", line 322, in _on_roi_layer_data_changed
    self.save()
  File "/home/dan/miniconda3/envs/napari_roi/lib/python3.9/site-packages/napari_roi/_roi_widget.py", line 443, in save
    "Name": [roi.name for roi in self._roi_layer_accessor],
  File "/home/dan/miniconda3/envs/napari_roi/lib/python3.9/site-packages/napari_roi/_roi_widget.py", line 443, in <listcomp>
    "Name": [roi.name for roi in self._roi_layer_accessor],
  File "/home/dan/miniconda3/envs/napari_roi/lib/python3.9/site-packages/napari_roi/_qt/roi_layer_accessor.py", line 110, in name
    self._parent._layer.properties[
KeyError: 'roi_name'
Aborted (core dumped)

**Comment by SchulzDan** [comment]
when adding rois with the draw rectangle tool there is no crash. it only happens when hitting the button "Add ROI" in otder to add a ROI of specified size

**Comment by jwindhager** [comment]
This should be fixed with the new napari version and the next immucan-roi release, therefore closing already
